### PR TITLE
Add build commands for arm and arm64

### PR DESCRIPTION
**Pull request by dmathieu**

### CODE REVIEW

**Comment by carlosedp** [comment]
Line 63 should be:

`cd $(GOPATH)/src/$(REPOPATH) && CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build --installsuffix cgo -ldflags="$(LDFLAGS)" -a -o $(BUILD_DIR)/configmap-reload-linux-arm64 configmap-reload.go`

Missed a "64" in arm64.

**Comment by dmathieu** [comment]
Good catch, thank you Carlos.

**Comment by carlosedp** [comment]
@dmathieu have you seen the errors  I reported on https://github.com/jimmidyson/configmap-reload/issues/17 in any of your deployments?

**Comment by dmathieu** [comment]
No, but I haven't run it on arm64.

**Pull request closed without merging**
