### PR TITLE
Enable watching multiple directories.

### PR DESCRIPTION
**Pull request by wjkohnen**
*  flag package is not capable of accepting string slices as
   parameters, consider using github.com/spf13/pflag instead.
*  Use arguments instead of parameters for volumeDir, so we can accept
   string slice for volume directories.
*  Emulate proper CLI documentation by overriding flag.Usage.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks for the PR! The flag package can accept slice flags - see https://golang.org/pkg/flag/#example_ fire an example of a custom slice flag. I'd prefer to keep flag rather than args so we can retain backwards compatibility. What do you think?

**Comment by wjkohnen** [comment]
Hey, thanks for coming back so quickly on this. I do agree about backwards compatibility. I've changed it, so one can give `--volume-dir` multiple times on the CLI, but I'll test it first (next week) before I update this PR or file another one. 

Somehow I forgot that one can construct custom flag types. :smiley:

**Comment by jimmidyson** [comment]
Cool thanks.

**Comment by wjkohnen** [comment]
superseeded by #5

**Pull request closed without merging**
