### PR TITLE
add help description

### PR DESCRIPTION
**Pull request by like-inspur**

### CODE REVIEW

**Review by migueleliasweb — COMMENTED** [review]
Looks good. Maybe it's worth changing the flag description and README text to match the other flags format by starting with lowercase letters?

**Comment by like-inspur** [comment]
@migueleliasweb  I have changed first word with lowercase letters

**Review by migueleliasweb — APPROVED** [review]
LGTM

**Comment by migueleliasweb** [comment]
Ping @jimmidyson

**Review by jimmidyson — APPROVED** [review]

**Comment by jimmidyson** [comment]
Thanks @like-inspur! And thanks @migueleliasweb for reviewing 🙏

**Pull request merged**
